### PR TITLE
feat: Return archive on /compress

### PR DESCRIPTION
**Pull request by GeekCornerGH**
I needed that so I made it myself, untested as it was in a rush (coding on phone is so awful)

### CODE REVIEW

**Comment by GeekCornerGH** [comment]
@BothimTV could you take a look at some point? Thanks in advance

**Comment by BothimTV** [comment]
Did you test the code? As far as I remember I would have needed to make another request in order to get the download url

**Comment by GeekCornerGH** [comment]
> Did you test the code? As far as I remember I would have needed to make another request in order to get the download url

It seems it worked, I'll retest again, but no, per the [docs](https://dashflo.net/docs/api/pterodactyl/v1/#req_810f2cd6853a4e31948d77f996e18f6d), it returns an object with a 200 response

**Comment by GeekCornerGH** [comment]
Update: Works as expected

**Review by BothimTV — APPROVED** [review]

**Pull request merged**
